import { 
  Users, 
  Loader2, 
  Home, 
  UserPlus, 
  CreditCard, 
  BarChart3, 
  Settings,
  LogOut,
  Menu,
  X,
  Plus,
  Edit,
  Trash2,
  Search,
  Filter,
  Download,
  Calendar,
  DollarSign,
  TrendingUp,
  AlertCircle,
  CheckCircle,
  Eye,
  FileText,
  PieChart,
  Activity,
  ChevronLeft
} from 'lucide-react';

export const Icons = {
  users: Users,
  spinner: Loader2,
  home: Home,
  userPlus: UserPlus,
  creditCard: CreditCard,
  barChart: BarChart3,
  settings: Settings,
  logOut: LogOut,
  menu: Menu,
  x: X,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  search: Search,
  filter: Filter,
  download: Download,
  calendar: Calendar,
  dollarSign: DollarSign,
  trendingUp: TrendingUp,
  alertCircle: AlertCircle,
  checkCircle: CheckCircle,
  eye: Eye,
  fileText: FileText,
  pieChart: PieChart,
  activity: Activity,
  chevronLeft: ChevronLeft,
};